#!/usr/bin/env python3
"""build_scenes.py: write a self-contained scenes.py for this reel.

scenes.py = the show-tell kit (iso_kit.py) + the 25 approved original props
(iso_originals_25.py), both copied unchanged from the brutalist.art checkout,
+ this film's scenes (scene_body.py). Gate A copies only scenes.py into its
sandbox, so nothing may be imported from beside it.

Usage: python3 build_scenes.py [path/to/brutalist.art]
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ART = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE.parents[2] / "brutalist.art"
KIT = ART / "skills" / "make" / "show-tell" / "templates"

parts = [
    "# GENERATED by build_scenes.py: edit scene_body.py, then rebuild. Do not edit this file.\n",
    (KIT / "iso_kit.py").read_text(),
    (KIT / "iso_originals_25.py").read_text(),
    (HERE / "scene_body.py").read_text(),
]
(HERE / "scenes.py").write_text("\n\n".join(parts))
print("wrote", HERE / "scenes.py")
